3.1. Rounding Numerical Values

In [1]:
round(1.23, 1)

1.2

In [2]:
round(1.27, 1)

1.3

In [3]:
round(-1.27, 1)

-1.3

In [4]:
round(1.25361, 3)

1.254

In [5]:
a = 1627731
round(a, -1)

1627730

In [6]:
round(a, -2)

1627700

In [7]:
x = 1.23456
format(x, '0.2f')

'1.23'

In [8]:
format(x, '0.3f')

'1.235'

3.2. Performing Accurate Decimal Calculations

In [9]:
a = 4.2
b = 2.1
a+b

6.300000000000001

In [10]:
from decimal import Decimal
a = Decimal(str(a))
b = Decimal(str(b))

In [11]:
a+b

Decimal('6.3')

In [12]:
print(a+b)

6.3


In [13]:
(a + b) == Decimal('4.2')

False

In [14]:
nums = [1.23e+18, 1, -1.23e+18]
sum(nums)

0.0

In [15]:
import math
math.fsum(nums)

1.0

3.3. Formatting Numbers for Output

In [16]:
x = 1234.56789
format(x, '0.2f')

'1234.57'

In [17]:
format(x, '10.2f')

'   1234.57'

In [18]:
format(x, '>10.2f')

'   1234.57'

In [19]:
format(x, '<10.2f')

'1234.57   '

In [20]:
format(x, '^10.2f')

' 1234.57  '

In [21]:
format(x, ',')

'1,234.56789'

In [22]:
format(x, '0,.1f')

'1,234.6'

In [23]:
format(x, 'e')

'1.234568e+03'

In [24]:
format(x, '0.2e')

'1.23e+03'

In [25]:
'This value is {:0,.2f}'.format(x)

'This value is 1,234.57'

In [27]:
swap_separators = { ord('.'): ',', ord(','): '.'}
format(x, ',').translate(swap_separators)

'1.234,56789'

In [28]:
format(1234567890.12345, ',').translate(swap_separators)

'1.234.567.890,12345'

3.4. Working with Binary, Octal, and Hexadecimal Integers

In [29]:
x = 1234
bin(x)

'0b10011010010'

In [30]:
oct(x)

'0o2322'

In [31]:
hex(x)

'0x4d2'

In [32]:
format(x, 'b')

'10011010010'

In [33]:
format(x, 'o')

'2322'

In [34]:
format(x, 'x')

'4d2'

In [35]:
x = -1234
format(x, 'b')

'-10011010010'

In [36]:
x = -1234
format(2**32 + x, 'b')

'11111111111111111111101100101110'

In [37]:
format(2**32 + x, 'x')

'fffffb2e'

In [38]:
int('4d2', 16)

1234

In [39]:
int('10011010010', 2)

1234

3.5. Packing and Unpacking Large Integers from Bytes Problem

In [40]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
len(data)

16

In [41]:
int.from_bytes(data, 'little')

69120565665751139577663547927094891008

In [42]:
int.from_bytes(data, 'big')

94522842520747284487117727783387188

In [46]:
x = 94522842520747284487117727783387188
x.to_bytes(16, 'big')

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [48]:
x = 69120565665751139577663547927094891008
x.to_bytes(16, 'little')

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [53]:
import struct
hi, lo = struct.unpack('>QQ', data)
(hi << 64) + lo

94522842520747284487117727783387188

In [55]:
x = 0x01020304
x.to_bytes(4, 'big')

b'\x01\x02\x03\x04'

In [56]:
x.to_bytes(4, 'little')

b'\x04\x03\x02\x01'

3.6. Performing Complex-Valued Math

In [57]:
a = complex(2, 4)
b = 3 - 5j
a + b

(5-1j)

In [58]:
a.real

2.0

In [59]:
a.imag

4.0

In [60]:
a.conjugate()

(2-4j)

In [61]:
import cmath
cmath.sin(a)

(24.83130584894638-11.356612711218174j)

3.7. Working with Infinity and NaNs

In [62]:
a = float('inf')
a

inf

In [63]:
math.isinf(a)

True

In [64]:
b = float('nan')
b

nan

In [65]:
math.isnan(b)

True

3.8. Calculating with Fractions

In [68]:
from fractions import Fraction
a = Fraction(5, 4)
b = Fraction(7, 16)
print(a + b)

27/16


In [69]:
c = a * b
c.numerator

35

In [70]:
float(c)

0.546875

In [75]:
print(c.limit_denominator(8))

4/7


In [77]:
x = 3.75
y = Fraction(*x.as_integer_ratio())
y

Fraction(15, 4)

3.9. Calculating with Large Numerical Arrays

In [78]:
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
x * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [79]:
x + y

[1, 2, 3, 4, 5, 6, 7, 8]

In [80]:
import numpy as np
ax = np.array(x)
ay = np.array(y)
ax * 2

array([2, 4, 6, 8])

In [81]:
ax + ay

array([ 6,  8, 10, 12])

In [82]:
def f(x):
    return 3*x**2 - 2*x + 7
f(ax)

array([ 8, 15, 28, 47])

3.10. Performing Matrix and Linear Algebra Calculations

In [83]:
import numpy as np
m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])

In [85]:
np.linalg.det(m)

-229.99999999999983

In [86]:
np.linalg.eigvals(m)

array([-13.11474312,   2.75956154,   6.35518158])

In [87]:
v = np.matrix([[2],[3],[4]])

In [88]:
x = np.linalg.solve(m, v)

In [89]:
x

matrix([[ 0.96521739],
        [ 0.17391304],
        [ 0.46086957]])

In [90]:
np.dot(m, x)

matrix([[ 2.],
        [ 3.],
        [ 4.]])

In [91]:
m * x

matrix([[ 2.],
        [ 3.],
        [ 4.]])

In [93]:
import random
values = [1, 2, 3, 4, 5, 6]
random.choice(values)

5

In [94]:
random.sample(values, 3)

[6, 4, 5]

In [96]:
random.shuffle(values)
values

[3, 6, 1, 4, 5, 2]

In [99]:
random.randint(0, 10)

7

In [100]:
random.random()

0.3305325645953997

3.12. Converting Days to Seconds, and Other Basic Time Conversions

In [103]:
from datetime import timedelta
a = timedelta(days=2, hours=6)
b = timedelta(hours=4.5)
c = a + b

In [104]:
c.days

2

In [105]:
c.seconds

37800

In [106]:
c.seconds / 60 / 60

10.5

In [107]:
c.total_seconds()

210600.0

In [109]:
from datetime import datetime
a = datetime(2012, 9,23)
print(a + timedelta(days=10))

2012-10-03 00:00:00


In [110]:
b = datetime(2012, 12, 21)
d = b - a
d.days

89

In [112]:
now = datetime.today()
print(now)

2018-01-31 11:24:18.032142


In [113]:
print(now + timedelta(minutes=19))

2018-01-31 11:43:18.032142


In [114]:
a = datetime(2012, 3, 1)
b = datetime(2012, 2, 28)
a - b

datetime.timedelta(2)

In [115]:
a = datetime(2012, 9, 23)
a + timedelta(months=1)

TypeError: 'months' is an invalid keyword argument for this function

In [119]:
from dateutil.relativedelta import relativedelta
a + relativedelta(months=+1)

datetime.datetime(2012, 10, 23, 0, 0)

In [120]:
a + relativedelta(months=-1)

datetime.datetime(2012, 8, 23, 0, 0)

In [125]:
b = datetime(2012, 12, 21)
d = b - a
d

datetime.timedelta(89)

In [126]:
d = relativedelta(b, a)

In [128]:
d.months

2

3.13. Determining Last Friday’s Date

In [134]:
from datetime import datetime, timedelta
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
def get_previous_byday(dayname, start_date=None):
    if start_date is None:
        start_date = datetime.today()
    day_num = start_date.weekday()
    day_num_target = weekdays.index(dayname)
    days_ago = ( 7 + day_num - day_num_target) % 7
    if days_ago == 0:
        days_ago = 7
    target_date = start_date - timedelta(days=days_ago)
    return target_date

In [135]:
datetime.today()

datetime.datetime(2018, 1, 31, 11, 39, 30, 378722)

In [136]:
get_previous_byday('Monday')

datetime.datetime(2018, 1, 29, 11, 39, 30, 890144)

In [137]:
get_previous_byday('Wednesday')

datetime.datetime(2018, 1, 24, 11, 40, 8, 249136)

In [138]:
get_previous_byday('Friday')

datetime.datetime(2018, 1, 26, 11, 40, 13, 400264)

In [139]:
d = datetime.now()

In [142]:
from dateutil.rrule import *
d + relativedelta(weekday=FR)

datetime.datetime(2018, 2, 2, 11, 41, 0, 227970)

In [144]:
d + relativedelta(weekday=FR(-1))

datetime.datetime(2018, 1, 26, 11, 41, 0, 227970)

3.14. Finding the Date Range for the Current Month

In [148]:
from datetime import datetime, date, timedelta
import calendar
def get_month_range(start_date=None):
    if start_date is None:
        start_date = date.today().replace(day=1)
    _, days_in_month = calendar.monthrange(start_date.year, start_date.month)
    end_date = start_date + timedelta(days=days_in_month)
    return (start_date, end_date)

In [149]:
a_day = timedelta(days=1)
first_day, last_day = get_month_range()
while first_day < last_day:
    print(first_day)
    first_day += a_day

2018-01-01
2018-01-02
2018-01-03
2018-01-04
2018-01-05
2018-01-06
2018-01-07
2018-01-08
2018-01-09
2018-01-10
2018-01-11
2018-01-12
2018-01-13
2018-01-14
2018-01-15
2018-01-16
2018-01-17
2018-01-18
2018-01-19
2018-01-20
2018-01-21
2018-01-22
2018-01-23
2018-01-24
2018-01-25
2018-01-26
2018-01-27
2018-01-28
2018-01-29
2018-01-30
2018-01-31


In [153]:
def date_range(start, stop, step):
    while start <= stop:
        yield start
        start += step

In [154]:
for d in date_range(date(2018, 1, 21), date.today(), step=timedelta(days=1)):
    print(d)

2018-01-21
2018-01-22
2018-01-23
2018-01-24
2018-01-25
2018-01-26
2018-01-27
2018-01-28
2018-01-29
2018-01-30
2018-01-31


3.15. Converting Strings into Datetimes

In [158]:
from datetime import datetime
text = '2012-09-20'
y = datetime.strptime(text, '%Y-%m-%d')
z = datetime.now()
d = z - y

In [161]:
d.days

1959

In [162]:
d.seconds

43167

In [164]:
d.microseconds

967946

In [163]:
d

datetime.timedelta(1959, 43167, 967946)

In [165]:
datetime.strftime(z, '%A %B %d %Y')

'Wednesday January 31 2018'

3.16. Manipulating Dates Involving Time Zones

In [166]:
from datetime import datetime
from pytz import timezone
d = datetime(2012, 12, 21, 9, 30, 0)
d

datetime.datetime(2012, 12, 21, 9, 30)

In [175]:
pacific = timezone('US/Pacific')
central = timezone('US/Central')

In [176]:
d_pacific = pacific.localize(d)
d_pacific

datetime.datetime(2012, 12, 21, 9, 30, tzinfo=<DstTzInfo 'US/Pacific' PST-1 day, 16:00:00 STD>)

In [177]:
d_pacific.astimezone(central)

datetime.datetime(2012, 12, 21, 11, 30, tzinfo=<DstTzInfo 'US/Central' CST-1 day, 18:00:00 STD>)